### ISSUE TITLE
Feature#001 - Posibilidad de añadir una tercera coordenada

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#1]
- Hacer que la clase point soporte coordenadas tridimensionales (x,y,z).
- Añadir los tests pertinentes.

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/1.-Clase-Point#feature001)

**Comment by ricardossmadrid** [comment]
Buenas noches,

He modificado el método phase() de la clase Point para volver a la versión anterior de éste, al igual que en la clase PointTest.
He pasado los test relacionados con dicha clase en local satisfactoriamente, mergeado con develop.
Una vez realizado, he hecho push para actualizar el repositorio y pasado todos los test en éste, ahora sin errores.

@fer2d2, dejo en tus manos cerrar la issue, si crees que está todo correcto.

Por favor, si ves algún punto mejorable házmelo saber.

Gracias por todo y un saludo,

Ricardo Sánchez

**Comment by fer2d2** [comment]
Hola Ricardo,

Cierro tus issue a falta de echar un vistazo a los tests para verificar que la cobertura es buena.

Gracias a ti por tu tiempo y por tu rápida capacidad de respuesta.

¡Un saludo!
