### ISSUE TITLE
Feature#004 - Permitir la obtención del elemento de la colección de menor valor

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#10]
- Permitir la obtención del elemento de la colección de menor valor.
- Codificar las pruebas pertinentes.

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/2.-Clase-DecimalCollection#feature004)

**Comment by jimeneztion** [comment]
Realizacion de la clase OK, merge con develop
