### ISSUE TITLE
Feature#007 - Creación de método isEquivalente()

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#11]
- Creación de método isEquivalente()
- Codificar los tests pertinentes

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/4.-Clase-Fraction#feature007)

**Comment by jimeneztion** [comment]
El metodo debe devolver un boolean o una fraccion?

**Comment by fer2d2** [comment]
Un booleano. En el caso de los otros métodos igual. Me he confundido, con tanto copy-pasteo y programar de noche...

Gracias por el aviso Sergio :)

**Comment by jimeneztion** [comment]
Nada, Ok ;)

**Comment by fer2d2** [comment]
He actualizado la documentación de la wiki, ¡Gracias de nuevo!

**Comment by jimeneztion** [comment]
Realizacion de la clase OK, subido a develop

**Comment by fer2d2** [comment]
Hola Sergio,

Necesito que revises dos cosas:
- El método isEquivalente no es correcto. La descripción:

> Dos fracciones son equivalentes cuando el producto de extremos (numerador de la primera por denominador de la segunda) es igual al producto de medios (denominador de la primera por el numerador de la segunda)

Tu método:

``` java
    public boolean isEquivalente(Fraction candidate) {
        return ((candidate.numerator == this.numerator) && (candidate.denominator == this.denominator));
    }
```

También necesito que añadas un par de correcciones rápidas en la clase UserTest. Hay dos test que no empiezan por la palabra test: `fullNameWithInitial` y `nameUppercase`.

¿Puedes echarle un vistazo? Haz las correcciones en ramas separadas, una para actualizar el isEquivalente (puede ser tu rama de la propia feature, simplemente tendrías que bajártela de origin) y otra para la corrección del test que te comento.

Muchas gracias.

**Comment by jimeneztion** [comment]
Ok, se cambia el metodo con las especificaciones mandadas y creación de nueva rama para el caso de los test
