### ISSUE TITLE
Feature#008 - Creación de método isPropia()

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#12]
- Creación de método `isPropia()`, que calcule si la fracción actual es propia. (numerador < denominador)
- Codificar los tests pertinentes

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/4.-Clase-Fraction#feature008)

**Comment by fer2d2** [comment]
Buenos días Ricardo:

He visto el problema que estás teniendo y he detectado varias cosas:
- Fallan tests de distintas clases. Tienes que pasar los tests en tu local antes de hacer push a origin/develop, y que dichos tests pasen tanto en tu local como en remoto. En remoto puedes ver los resultados aquí: https://travis-ci.org/fer2d2/SpaiEcp2FernandoMoroHernandez.
- Mientras un test falle en develop, **eso significa que nuestra feature no es estable y tienes que trabajar en que los tests pasen**.
- En el comentario de un ticket anterior os explicaba que sólo teníais que hacer merge de vuestra rama Feature#xxx con develop, **y que del merge con master (integración a la rama de producción) me encargaba yo cuando planificase la Release**. Y es más, nunca se puede integrar en esa rama si los tests de develop fallan, ya que estaríamos rompiendo la cadena de integración continua.
- He bloqueado temporalmente el push a master, porque intuyo que mientras vamos acostumbrándonos a este workflow, vamos a cometer bastantes errores.

Por todas estas razones voy a revertir tu merge en master, de modo que quede en el punto en que yo lo dejé, y te pido que por favor revises tus cambios en develop hasta que todos los tests pasen.

Gracias por tu tiempo y perdona por el texto tan largo...

¡Un saludo!

**Comment by fer2d2** [comment]
Aprovecho también para pedirte que me dejes un comentario en los distintos tickets, para poder ir cerrándolos yo y así controlar las milestones :)

Si necesitas cualquier tipo de ayuda o aclaración no dudes en hablarlo por aquí.

**Comment by ricardossmadrid** [comment]
Buenas tardes Fernando,

Muchas gracias por la aclaración. La verdad, es la primera vez que utilizo la herramienta y, como he leído que comentabas, la combinación con trabajar de noche no siempre sale bien.

Voy a trabajar en ello ahora mismo

Una vez más muchas gracias y un saludo,

Ricardo Sánchez

**Comment by ricardossmadrid** [comment]
Buenas noches,

He incluido el método isPropia() a la clase Fraction y el test pertinente en la clase FractionTest.

Los test han sido pasados, primero en local y posteriormente en remoto, en la rama develop, satisfactoriamente.

Gracias y un saludo,

Ricardo Sánchez
