### ISSUE TITLE
Feature#009 - Creación de métodos isMayor() e isMenor()

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#13]
- Codificación de sendos métodos
- Codificación de las pruebas pertinentes

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/4.-Clase-Fraction#feature009)

**Comment by RaquelDiazG** [comment]
He realizado los métodos pedidos en la rama Feature#005.
He pasado mi test y como todo pasaba he mergeado la rama a develop.
Cierro el issue
