### ISSUE TITLE
Fallo en testFase

### ISSUE THREAD

**Issue by RaquelDiazG** [fer2d2/SpaiEcp2FernandoMoroHernandez#14]
Al pasar la suite de test, hay un fallo en el siguiente test:

``` javascript
@Test
    public void testFase() {
        assertEquals(0.3363, pt.phase(), 10e-5);
    }
```

**Comment by fer2d2** [comment]
Sí, pero es debido a que el compañero que ha hecho la parte de añadir una tercera coordenada no ha cambiado ese test para que pase. Por ello el test explota.

En producción (antes de los cambios) pasa, tal y como muestra el registro en travis-ci.

**Comment by fer2d2** [comment]
@RaquelDiazG @ricardossmadrid @sergioMIW 
Os adjunto lo que comentaba:
https://travis-ci.org/fer2d2/SpaiEcp2FernandoMoroHernandez/branches

En master los tests pasaban hasta que se hizo la ampliación de la clase Point. Necesitamos que Ricardo lo corrija (como sabéis yo no puedo tocar código). Si no lo puede abordar os lo tendré que reasignar (realmente es cuestión de cambiar una prueba, creo, para que contraste el resultado con el que debería dar una coordenada tridimensional).

Os comento otra cosa para que la tengáis en cuenta a futuro:
- Normalmente cuando no pasan los tests en local no se integra en la rama develop, aunque pasen nuestros test y sean los de un compañero los que fallan. Travis es un sistema de CI permisivo, pero hay otros sistemas que ni siquiera dejan hacer merge en develop a menos que pasen todos los tests, como jenkins.
- El flujo de trabajo normal en estos casos sería abrir un issue avisando al responsable y esperar a que lo resuelva, o bien resolverlo nosotros si nos urge integrar.

Aprovecho para comentaros que no era necesario subir las ramas Feature, pero no os preocupéis por eso, las eliminaré antes del hito de preparación de la release.

**Comment by RaquelDiazG** [comment]
Sí, yo he creado el issue para tener en cuenta que es un bug que hay que arreglar.
Y otra cosa, creo que es buena idea subir todas las ramas feature y no borrarlas posteriormente, ya que así podemos tener un reflejo de cómo ha ido el desarrollo, pero bueno, es solo un consejo :)

**Comment by ricardossmadrid** [comment]
Buenas tardes a todos,

Siento el pequeño fallo que he tenido con este método.

Tengo realmente dudas de qué hace el método phase() de la clase Point y de cómo integrarle la tercera coordenada.

@fer2d2, ¿me podrías exponer la función a realizar?

Muchas gracias y un saludo,

Ricardo Sánchez

**Comment by fer2d2** [comment]
Hola @ricardossmadrid,

He estado revisando el problema, y es más complejo de lo que yo en principio pensaba. Me temo que no es trivial calcular el ángulo (_phase_) de una coordenada tridimensional, pues hay que utilizar un tipo de coordenadas especiales: o coordenadas esféricas o coordenadas cilíndricas:
https://es.wikipedia.org/wiki/Coordenadas_polares#Tres_dimensiones

Esto es mucho trabajo y escapa al dominio de esta práctica, de modo que vamos a entender que se utiliza un sistema de coordenadas cilíndricas, y que la phase (que es lo que llaman θ), sigue siendo el ángulo formado entre los ejes X y Y, de acuerdo a lo que se muestra en la siguiente imagen:

![Coordenadas cilíndricas](http://mathworld.wolfram.com/images/eps-gif/ParabolicCylindricalCoords_1100.gif)

Para ello tendrás que dejar el método `phase()` como inicialmente estaba.

Siento que se haya ido tanto de las manos, este tipo de cosas no se pueden prever fácilmente.

Una vez lo tengas hecho, prueba a pasar los tests y si todo funciona adecuadamente, puedes integrar en develop.

Muchas gracias y disculpa por las molestias.
