### ISSUE TITLE
Subida ramas Feature#xxx

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#17]
Hola @RaquelDiazG @ricardossmadrid @sergioMIW 

He mandado un correo a Jesús Bernal consultando el tema de las ramas Feature#xxx y me ha dicho que las dejéis en origin, tal y como comentaba @RaquelDiazG, ya que le interesa tener un "rastreo" de lo que habéis hecho. 

Creo que lo habéis hecho todos menos @ricardossmadrid, pero os lo comento a todos para que lo podáis revisar.

Gracias por vuestro tiempo.

¡Un saludo!

**Comment by fer2d2** [comment]
Efectivamente, creo que faltan Features 1, 2 y 8.

**Comment by ricardossmadrid** [comment]
Buenas tardes,

Las ramas 1, 2 y 8 las eliminé en local cuando las hice "merge" con develop, tal y como lo vi hacer a Jesus en sus clases, lo cual me imposibilita su subida. La nueva feature si la he podido subir sin problemas.

Un saludo y gracias
