### ISSUE TITLE
Subir features faltantes

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#18]
Hola @ricardossmadrid 

He estado dándole una vuelta a cómo puedes hacer para subir las ramas que eliminaste. Hay un pequeño truco. Yo sé hacerlo en línea de comandos, así que te explico cómo se hace por si puedes replicarlo con eclipse:

Cada rama no es más que un puntero a un commit específico, y la lista de commits es la siguiente:
https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/commits/master

Si quieres por ejemplo regenerar la rama Feature#001, simplemente tienes que crear una rama apuntando a ese commit y subirla a origin. Imagina que la Feature#001 es una rama que estaba apuntando al commit `87f5ee1`, que tiene el texto `Se incluyen los test para la clase punto modificada`.
- Todo lo que tienes que hacer es moverte a ese commit, lo que en Eclipse se hace haciendo clic en el commit (en línea de comandos sería `git checkout 87f5ee1`).
- Luego, una vez que estás en ese commit, creas una rama apuntando a él. En Eclipse ya sabes cómo se hace. En línea de comandos sería `git checkout -b Feature#001`.
- Finalmente subes la rama a origin. En Eclipse ya sabes cómo es. Con línea de comandos: `git push origin Feature#001`

Hazlo con los commits pertinentes, y ya lo tendrías resuelto. ¡Gracias!

**Comment by ricardossmadrid** [comment]
Buenas tardes @fer2d2 

He creado subido las ramas al repositorio remoto.

He añadido las ramas una vez se han terminado por completo las ampliaciones de cada clase asignadas a mi, con lo que son:

Feature#001
Feature#002NuevoTest
Feature#008

Espero esté todo a tu gusto. SI no es así, por favor, me lo comentas y lo modifico.

Cierro la issue.

Gracias por todo y un saludo,

Ricardo Sánchez
