### ISSUE TITLE
Feature#002 - Permitir modificación de coordenadas

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#2]
- Permitir modificar los datos de una coordenada en tiempo de ejecución.
- Probar la nueva funcionalidad.

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/1.-Clase-Point#feature002)

**Comment by ricardossmadrid** [comment]
Buenas noches,

He incluido los nuevos métodos (setX, setY y setZ) a la clase Point y mergeado con develop,dando por terminada la issue.

Muchas gracias y un saludo,

Ricardo Sánchez

**Comment by fer2d2** [comment]
Buenos días @ricardossmadrid,

Estaba revisando este punto y he visto que no has preparado tests para él. Aunque son setters, lo he consultado y creo que estaría bien añadir una prueba sencilla.

Yo me he visto en la misma situación que tú y he seguido una estrategia muy sencilla, me ha llevado un par de minutos: comprobar el resultado del test antes y despúes de usar los setters, para demostrar que se produce el cambio en tiempo de ejecución:

```
// pseudocódigo
testUpdateCoordinate() {
  // before
  assertEquals(...)
  // update
  point.set...
  // after
  assertEquals(...)
}
```

¿Podrías añadir este test? Me gustaría que todo lo que se ha ido incluyendo tenga cobertura para sacar la release con un _test-coverage_ del 100%.

¡Gracias!

**Comment by fer2d2** [comment]
También necesito que alguien elimine el ficherito **empty.txt** del package de los tests, ¿Te importaría hacerlo aprovechando la coyuntura?

De nuevo muchas gracias y disculpa por las molestias.

**Comment by ricardossmadrid** [comment]
Buenas tardes,

He incluido el test pertinente para la inclusión del testSetters en la clase PointTest.

He pasado los test en local y al hacer push se han pasado correctamente en travis.

Por favor, @fer2d2 échale un vistazo y si debo hacer alguna tarea más no dudes en decírmelo.

Gracias y saludos,

Ricardo Sánchez

**Comment by ricardossmadrid** [comment]
Una cosa más, he borrado el fichero empty.txt en la misma rama..

Saludos
