### ISSUE TITLE
Feature#006 - Mostrar nombre completo con diversos formatos

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#5]
- Incluir métodos con otras formas de presentar el nombre completo
- Codificar los tests pertinentes

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/3.-Clase-User#feature006)

**Comment by RaquelDiazG** [comment]
He realizado los métodos pedidos en la rama Feature#006.
He pasado mis test y como todos pasaban he mergeado la rama a develop.
Cierro el issue
