### ISSUE TITLE
Feature#005 - Presentar el nombre en mayúsculas

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#6]
- Presentar el nombre en mayúsculas
- Codificar los tests pertinentes

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/3.-Clase-User#feature005)

**Comment by sergioMIW** [comment]
Buenas,
Necesito que inicialmente realizes los test de las clases principales antes de empezar al desarrollo de las funcionalidades.

PDF: Es responsabilidad del arquitecto realizar los test de cada clase en su versión inicial

Un saludo, gracias

**Comment by sergioMIW** [comment]
Buenas,
Necesito que inicialmente realizes los test de las clases principales antes de empezar al desarrollo de las funcionalidades.

PDF: Es responsabilidad del arquitecto realizar los test de cada clase en su versión inicial

Un saludo, gracias.

PD: Cuando lo realizes vuelve a abrirme la incidencia para que se me notifique

**Comment by fer2d2** [comment]
Hola Sergio,

- Espero tener subidos los test mañana.
- Inicialmente las issue están abiertas pero no asignadas a ningún programador, ya que sin tener los tests no podía tampoco pararme a pensar en la planificación.
- Lo lógico sería abrir una nueva Issue bajo la categoría "question" para tratar esto que comentas y asignarte a ella.

Procedo a hacerlo así y dejar este issue como abierto.

¡Un saludo y gracias!

**Comment by RaquelDiazG** [comment]
He realizado los métodos pedidos en la rama Feature#005.
He pasado mi test y como todo pasaba he mergeado la rama a develop.
Cierro el issue
