### ISSUE TITLE
Feature#003 - Permitir el cálculo de la media de los elementos que componen la colección

### ISSUE THREAD

**Issue by fer2d2** [fer2d2/SpaiEcp2FernandoMoroHernandez#9]
- Permitir el cálculo de la media de los elementos que componen la colección.
- Elaborar las pruebas pertinentes.

[Ver más información en WIKI](https://github.com/fer2d2/SpaiEcp2FernandoMoroHernandez/wiki/2.-Clase-DecimalCollection#feature003)

**Comment by jimeneztion** [comment]
He realizado los métodos pedidos en la rama Feature#003.
test OK , merge a develop.
Cierro el issue
